services:
  db.configbay:
    image: postgres:16-bullseye
    restart: always
    container_name: db.configbay
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend_bridge
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ../asset/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api.configbay:
    depends_on:
      - db.configbay
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        GOOS: linux
        GOARCH: amd64
        GO_VERSION: 1.21
    container_name: api.configbay
    environment:
      CONF_PATH: ${CONF_PATH}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      IS_CONTAINER: ${IS_CONTAINER}
    networks:
      - backend_bridge
    volumes:
      - api_volume:/etc/runtime/configbay
    ports:
      - "8000:8000"

volumes:
  api_volume:
  db_volume:

networks:
  backend_bridge: