# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Build-Test-Api

on:
  push:
    branches: [ "main", "dev", "devops/ci/test" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-test-api:
    runs-on: debian-bookworm
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      env: 
        GOOS: linux
        GOARCH: amd64
        POSTGRES_DB: ${{ env.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        CONF_PATH: ${{ env.CONF_PATH }}
      run: make build-api
      
    - name: Test
      run: make test-api
      
